version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customer-service
    ports:
      - "6789:6789"
    depends_on:
      - customer-database
    networks:
      - customers_network

  customer-database:
    image: postgres:latest
    container_name: customer-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "4213:5432"
    networks:
      - customers_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./configs/migrations:/docker-entrypoint-initdb.d
volumes:
  postgres_data:

networks:
  customers_network:
    driver: bridge
