services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db  # Certifique-se de que o banco de dados esteja disponível antes do aplicativo web iniciar
    networks:
      - customers_service_network
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - customers_service_network
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volume para persistir dados do PostgreSQL
      - ./scripts:/docker-entrypoint-initdb.d
volumes:
  postgres_data:  # Volume persistente para PostgreSQL
networks:
  customers_service_network:  # Rede de contêiner
    driver: bridge
